### ISSUE TITLE
Running locally without authentication?

### ISSUE THREAD

**Issue by HEnquist** [transcelerate/ddf-sdr-ui#100]
We are trying to run the whole ddf-sdr system (db, api and ui) on a local machine.
When attempting to run the ui, we have issues with authentication.
Is there a way to disable the authentication? If not, is that something that could be implemented? 
This would make it much easier for developers or anyone wanting to try out the app.

**Comment by sdr-support** [comment]
@HEnquist Thank you for reaching out to SDR Team. Please find a ticket we have raised in the SDR Support repo for your query. https://github.com/transcelerate/ddf-sdr-support/issues/27
We shall correspond on this in the above ticket. Please feel free to also reach out to us on sdr.support@accenture.com

For future support tickets you can raise issues [here](https://github.com/transcelerate/ddf-sdr-support/issues/new/choose)

**Comment by HEnquist** [comment]
Solved in the linked issue.
