### ISSUE TITLE
Package installation is failed

### ISSUE THREAD

**Issue by seyama-daisuke** [transcelerate/ddf-sdr-ui#226]
Hello, I'd like to test this study builder UI, but I'm facing a problem.

Based on your README, I ran "npm install" command in SDR-WebApp directory.
But, installation was failed by some errors as bellow.

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @azure/msal-angular@2.0.5
npm ERR! Found: rxjs@7.4.0
npm ERR! node_modules/rxjs
npm ERR!   rxjs@"~7.4.0" from the root project
npm ERR!   peer rxjs@"^6.5.3 || ^7.4.0" from @angular/cdk@13.3.7
npm ERR!   node_modules/@angular/cdk
npm ERR!     @angular/cdk@"^13.1.1" from the root project
npm ERR!     peer @angular/cdk@"13.3.7" from @angular/material@13.3.7
npm ERR!     node_modules/@angular/material
npm ERR!       @angular/material@"^13.3.7" from the root project
npm ERR!   8 more (@angular/common, @angular/core, @angular/forms, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer rxjs@"^6.0.0" from @azure/msal-angular@2.0.5
npm ERR! node_modules/@azure/msal-angular
npm ERR!   @azure/msal-angular@"^2.0.5" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: rxjs@6.6.7
npm ERR! node_modules/rxjs
npm ERR!   peer rxjs@"^6.0.0" from @azure/msal-angular@2.0.5
npm ERR!   node_modules/@azure/msal-angular
npm ERR!     @azure/msal-angular@"^2.0.5" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

I tried "main" and "release" branches, but I got same error.
Do you have some solutions ?

My environment:
* Windows 10
* npm -v >> 9.5.1
* node -v >> v18.16.0

**Comment by InduSekharSajja** [comment]
@seyama-daisuke : Thank you for reaching out to SDR Team. Please find a ticket we have raised in the SDR Support repo for your query. https://github.com/transcelerate/ddf-sdr-support/issues/38
We shall correspond on this in the above ticket. Please feel free to also reach out to us on [sdr.support@accenture.com](mailto:sdr.support@accenture.com)

For future support tickets you can raise issues [here](https://github.com/transcelerate/ddf-sdr-support/issues/new/choose)

**Comment by sdr-support** [comment]
@seyama-daisuke The ticket https://github.com/transcelerate/ddf-sdr-support/issues/38 has been updated with steps to overcome issue faced during npm install.

**Comment by seyama-daisuke** [comment]
As commented bellow, this issue has been resolved by W.A.
Thank you.

https://github.com/transcelerate/ddf-sdr-support/issues/38#issuecomment-1618287887
